#Server Port
server:
  port: 8086

# Configuration Postgres and Spring Data JPA
spring:
  datasource:
    password: admin123
    username: postgres
    url: jdbc:postgresql://localhost:5432/product_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #Configuration Security Oauth 2
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8084/oauth2/jwks

  #Application Name
  application:
    name: product-service

# Configuration Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true




